package entity;
// Generated Dec 5, 2019 10:39:33 PM by Hibernate Tools 4.3.1



/**
 * CanCommentOnId generated by hbm2java
 */
public class CanCommentOnId  implements java.io.Serializable {


     private String customerUsername;
     private int movieSerialNo;

    public CanCommentOnId() {
    }

    public CanCommentOnId(String customerUsername, int movieSerialNo) {
       this.customerUsername = customerUsername;
       this.movieSerialNo = movieSerialNo;
    }
   
    public String getCustomerUsername() {
        return this.customerUsername;
    }
    
    public void setCustomerUsername(String customerUsername) {
        this.customerUsername = customerUsername;
    }
    public int getMovieSerialNo() {
        return this.movieSerialNo;
    }
    
    public void setMovieSerialNo(int movieSerialNo) {
        this.movieSerialNo = movieSerialNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CanCommentOnId) ) return false;
		 CanCommentOnId castOther = ( CanCommentOnId ) other; 
         
		 return ( (this.getCustomerUsername()==castOther.getCustomerUsername()) || ( this.getCustomerUsername()!=null && castOther.getCustomerUsername()!=null && this.getCustomerUsername().equals(castOther.getCustomerUsername()) ) )
 && (this.getMovieSerialNo()==castOther.getMovieSerialNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomerUsername() == null ? 0 : this.getCustomerUsername().hashCode() );
         result = 37 * result + this.getMovieSerialNo();
         return result;
   }   


}


