package entity;
// Generated Dec 8, 2019 12:24:52 PM by Hibernate Tools 4.3.1



/**
 * CanCommentOn generated by hbm2java
 */
public class CanCommentOn  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private Movie movie;

    public CanCommentOn() {
    }

    public CanCommentOn(Customer customer, Movie movie) {
       this.customer = customer;
       this.movie = movie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }




}


