package entity;
// Generated Dec 8, 2019 2:02:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CmsPage generated by hbm2java
 */
public class CmsPage  implements java.io.Serializable {


     private String pageTitle;
     private Manager manager;
     private String pageBody;
     private String pageTags;
     private String pageDesc;
     private Date modifiedDate;

    public CmsPage() {
    }

    public CmsPage(String pageTitle, Manager manager, String pageBody, String pageTags, String pageDesc, Date modifiedDate) {
       this.pageTitle = pageTitle;
       this.manager = manager;
       this.pageBody = pageBody;
       this.pageTags = pageTags;
       this.pageDesc = pageDesc;
       this.modifiedDate = modifiedDate;
    }
   
    public String getPageTitle() {
        return this.pageTitle;
    }
    
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }
    public Manager getManager() {
        return this.manager;
    }
    
    public void setManager(Manager manager) {
        this.manager = manager;
    }
    public String getPageBody() {
        return this.pageBody;
    }
    
    public void setPageBody(String pageBody) {
        this.pageBody = pageBody;
    }
    public String getPageTags() {
        return this.pageTags;
    }
    
    public void setPageTags(String pageTags) {
        this.pageTags = pageTags;
    }
    public String getPageDesc() {
        return this.pageDesc;
    }
    
    public void setPageDesc(String pageDesc) {
        this.pageDesc = pageDesc;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


