package entity;
// Generated Dec 8, 2019 2:02:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String username;
     private String password;
     private String email;
     private Date createdDate;
     private String address;
     private String visa;
     private Set canCommentOns = new HashSet(0);
     private Set reserveses = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String username, String password, String email, Date createdDate, String address, String visa) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.createdDate = createdDate;
        this.address = address;
        this.visa = visa;
    }
    public Customer(String username, String password, String email, Date createdDate, String address, String visa, Set canCommentOns, Set reserveses) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.createdDate = createdDate;
       this.address = address;
       this.visa = visa;
       this.canCommentOns = canCommentOns;
       this.reserveses = reserveses;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getVisa() {
        return this.visa;
    }
    
    public void setVisa(String visa) {
        this.visa = visa;
    }
    public Set getCanCommentOns() {
        return this.canCommentOns;
    }
    
    public void setCanCommentOns(Set canCommentOns) {
        this.canCommentOns = canCommentOns;
    }
    public Set getReserveses() {
        return this.reserveses;
    }
    
    public void setReserveses(Set reserveses) {
        this.reserveses = reserveses;
    }




}


