package entity;
// Generated Dec 8, 2019 2:02:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private String username;
     private String password;
     private String email;
     private Set cmsPages = new HashSet(0);
     private Set movies = new HashSet(0);

    public Manager() {
    }

	
    public Manager(String username, String password, String email) {
        this.username = username;
        this.password = password;
        this.email = email;
    }
    public Manager(String username, String password, String email, Set cmsPages, Set movies) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.cmsPages = cmsPages;
       this.movies = movies;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getCmsPages() {
        return this.cmsPages;
    }
    
    public void setCmsPages(Set cmsPages) {
        this.cmsPages = cmsPages;
    }
    public Set getMovies() {
        return this.movies;
    }
    
    public void setMovies(Set movies) {
        this.movies = movies;
    }




}


