package entity;
// Generated Dec 5, 2019 10:39:33 PM by Hibernate Tools 4.3.1



/**
 * Reserves generated by hbm2java
 */
public class Reserves  implements java.io.Serializable {


     private ReservesId id;
     private Customer customer;
     private Seat seat;

    public Reserves() {
    }

    public Reserves(ReservesId id, Customer customer, Seat seat) {
       this.id = id;
       this.customer = customer;
       this.seat = seat;
    }
   
    public ReservesId getId() {
        return this.id;
    }
    
    public void setId(ReservesId id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Seat getSeat() {
        return this.seat;
    }
    
    public void setSeat(Seat seat) {
        this.seat = seat;
    }




}


