package entity;
// Generated Dec 5, 2019 10:39:33 PM by Hibernate Tools 4.3.1



/**
 * ReservesId generated by hbm2java
 */
public class ReservesId  implements java.io.Serializable {


     private String customerUsername;
     private int seatNo;

    public ReservesId() {
    }

    public ReservesId(String customerUsername, int seatNo) {
       this.customerUsername = customerUsername;
       this.seatNo = seatNo;
    }
   
    public String getCustomerUsername() {
        return this.customerUsername;
    }
    
    public void setCustomerUsername(String customerUsername) {
        this.customerUsername = customerUsername;
    }
    public int getSeatNo() {
        return this.seatNo;
    }
    
    public void setSeatNo(int seatNo) {
        this.seatNo = seatNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservesId) ) return false;
		 ReservesId castOther = ( ReservesId ) other; 
         
		 return ( (this.getCustomerUsername()==castOther.getCustomerUsername()) || ( this.getCustomerUsername()!=null && castOther.getCustomerUsername()!=null && this.getCustomerUsername().equals(castOther.getCustomerUsername()) ) )
 && (this.getSeatNo()==castOther.getSeatNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomerUsername() == null ? 0 : this.getCustomerUsername().hashCode() );
         result = 37 * result + this.getSeatNo();
         return result;
   }   


}


