package entity;
// Generated Dec 8, 2019 1:55:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seat generated by hbm2java
 */
public class Seat  implements java.io.Serializable {


     private Integer seatNo;
     private TicketSeller ticketSeller;
     private int seatPrice;
     private Set reserveses = new HashSet(0);

    public Seat() {
    }

	
    public Seat(TicketSeller ticketSeller, int seatPrice) {
        this.ticketSeller = ticketSeller;
        this.seatPrice = seatPrice;
    }
    public Seat(TicketSeller ticketSeller, int seatPrice, Set reserveses) {
       this.ticketSeller = ticketSeller;
       this.seatPrice = seatPrice;
       this.reserveses = reserveses;
    }
   
    public Integer getSeatNo() {
        return this.seatNo;
    }
    
    public void setSeatNo(Integer seatNo) {
        this.seatNo = seatNo;
    }
    public TicketSeller getTicketSeller() {
        return this.ticketSeller;
    }
    
    public void setTicketSeller(TicketSeller ticketSeller) {
        this.ticketSeller = ticketSeller;
    }
    public int getSeatPrice() {
        return this.seatPrice;
    }
    
    public void setSeatPrice(int seatPrice) {
        this.seatPrice = seatPrice;
    }
    public Set getReserveses() {
        return this.reserveses;
    }
    
    public void setReserveses(Set reserveses) {
        this.reserveses = reserveses;
    }




}


